var srcIndex = JSON.parse('{\
"nautilus_backtest":["",[],["engine.rs","lib.rs"]],\
"nautilus_common":["",[["ffi",[],["clock.rs","logging.rs","mod.rs","msgbus.rs","timer.rs"]],["generators",[],["client_order_id.rs","mod.rs","order_list_id.rs","position_id.rs"]],["python",[],["mod.rs","timer.rs"]]],["clock.rs","enums.rs","handlers.rs","lib.rs","logging.rs","msgbus.rs","testing.rs","timer.rs"]],\
"nautilus_core":["",[["ffi",[],["cvec.rs","datetime.rs","mod.rs","parsing.rs","string.rs","uuid.rs"]],["python",[],["casing.rs","datetime.rs","mod.rs","serialization.rs","uuid.rs"]]],["correctness.rs","datetime.rs","lib.rs","message.rs","parsing.rs","serialization.rs","time.rs","uuid.rs"]],\
"nautilus_indicators":["",[["average",[],["ama.rs","dema.rs","ema.rs","mod.rs","sma.rs","wma.rs"]],["momentum",[],["mod.rs","rsi.rs"]],["python",[["average",[],["ama.rs","dema.rs","ema.rs","mod.rs","sma.rs","wma.rs"]],["momentum",[],["mod.rs","rsi.rs"]],["ratio",[],["efficiency_ratio.rs","mod.rs"]]],["mod.rs"]],["ratio",[],["efficiency_ratio.rs","mod.rs"]]],["indicator.rs","lib.rs"]],\
"nautilus_model":["",[["data",[],["bar.rs","delta.rs","mod.rs","order.rs","quote.rs","ticker.rs","trade.rs"]],["events",[],["mod.rs","order.rs","position.rs"]],["ffi",[["data",[],["bar.rs","delta.rs","mod.rs","order.rs","quote.rs","ticker.rs","trade.rs"]],["events",[],["mod.rs","order.rs"]],["identifiers",[],["account_id.rs","client_id.rs","client_order_id.rs","component_id.rs","exec_algorithm_id.rs","instrument_id.rs","mod.rs","order_list_id.rs","position_id.rs","strategy_id.rs","symbol.rs","trade_id.rs","trader_id.rs","venue.rs","venue_order_id.rs"]],["orderbook",[],["book.rs","level.rs","mod.rs"]],["types",[],["currency.rs","mod.rs","money.rs","price.rs","quantity.rs"]]],["enums.rs","mod.rs"]],["identifiers",[],["account_id.rs","client_id.rs","client_order_id.rs","component_id.rs","exec_algorithm_id.rs","instrument_id.rs","macros.rs","mod.rs","order_list_id.rs","position_id.rs","strategy_id.rs","symbol.rs","trade_id.rs","trader_id.rs","venue.rs","venue_order_id.rs"]],["instruments",[],["crypto_future.rs","crypto_perpetual.rs","currency_pair.rs","equity.rs","futures_contract.rs","mod.rs","options_contract.rs","synthetic.rs","synthetic_api.rs"]],["orderbook",[],["book.rs","ladder.rs","level.rs","mod.rs"]],["orders",[],["base.rs","default.rs","limit.rs","limit_if_touched.rs","market.rs","market_if_touched.rs","market_to_limit.rs","mod.rs","stop_limit.rs","stop_market.rs","trailing_stop_limit.rs","trailing_stop_market.rs"]],["python",[["data",[],["bar.rs","delta.rs","mod.rs","order.rs","quote.rs","ticker.rs","trade.rs"]],["identifiers",[],["instrument_id.rs","mod.rs"]],["instruments",[],["crypto_future.rs","crypto_perpetual.rs","currency_pair.rs","equity.rs","futures_contract.rs","mod.rs","options_contract.rs"]],["orders",[],["market.rs","mod.rs"]],["types",[],["currency.rs","mod.rs","money.rs","price.rs","quantity.rs"]]],["macros.rs","mod.rs"]],["types",[],["balance.rs","currency.rs","fixed.rs","mod.rs","money.rs","price.rs","quantity.rs"]]],["currencies.rs","enums.rs","lib.rs","macros.rs","position.rs"]],\
"nautilus_network":["",[["ratelimiter",[],["clock.rs","gcra.rs","mod.rs","nanos.rs","quota.rs"]]],["http.rs","lib.rs","socket.rs","websocket.rs"]],\
"nautilus_persistence":["",[["arrow",[],["bar.rs","delta.rs","mod.rs","quote.rs","trade.rs"]],["backend",[],["kmerge_batch.rs","mod.rs","session.rs"]],["python",[["backend",[],["mod.rs","session.rs","transformer.rs"]],["wranglers",[],["bar.rs","delta.rs","mod.rs","quote.rs","trade.rs"]]],["mod.rs"]]],["lib.rs"]],\
"nautilus_pyo3":["",[],["lib.rs"]],\
"tokio_tungstenite":["",[],["compat.rs","connect.rs","handshake.rs","lib.rs","stream.rs","tls.rs"]]\
}');
createSrcSidebar();
