GRANT CONNECT ON DATABASE postgres TO nautilus;
GRANT ALL PRIVILEGES ON SCHEMA public TO nautilus;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nautilus;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nautilus;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO nautilus;
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA public TO nautilus;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA public TO nautilus;

